<?
// l16n translations --------------------------------------------------------
$cmd = mysql_query("SET NAMES 'utf8'");
$cmd = mysql_query("SET CHARACTER SET 'utf8'");


$cmd = mysql_query("INSERT INTO `l16n` (`id`, `needle`, `en`, `de`, `fr`, `es`, `nl`, `dk`, `se`, `it`) VALUES
(1, '_open', 'Open:', 'Offen:', 'Ouvert: de', '', ' ', ' ', 'Öppet:', ' '),
(2, '_till', 'till', 'bis', 'jusqu´à', '', ' ', ' ', 'till', ' '),
(3, '_oclock', 'o clock', 'Uhr', ' ', '', ' ', ' ', 'Klockan', ' '),
(4, '_tautologous', 'Tautologous with', 'Doppelt gebucht mit', 'double reservation avec', '', ' ', ' ', 'DUBBELBOKAD med', ' '),
(5, '_day_comment', 'Day comment', 'Kommentar zum Tag', 'Commentaire du jour', '', ' ', ' ', 'Dag kommentar', ' '),
(6, '_add_seats', 'Add seats', 'Sitzplätze dazu', 'Ajouter sièges', '', ' ', ' ', 'Lägg till sittplatser', ' '),
(7, '_add_tables', 'Add tables', 'Tischanzahl dazu', 'Ajouter tables', '', ' ', ' ', 'Lägg till bord', ' '),
(8, '_capacity', 'Capacity', 'Kapazität', 'Capacité', '', ' ', ' ', 'Extra kapacitet', ' '),
(9, '_save', 'Save', 'speichern', 'sauvegarder', '', ' ', ' ', 'Spara', ' '),
(10, '_delete', 'Delete', 'löschen', 'effacer', '', ' ', ' ', 'Ta bort', ' '),
(11, '_reset', 'Reset', 'Reset', 'Recommencer', '', ' ', ' ', 'Reset', ' '),
(12, '_allow', 'Allow', 'erlauben', 'autoriser', '', ' ', '', 'Acceptera', ' '),
(13, '_edit', 'Edit', 'ändern', 'modifier', '', ' ', ' ', 'Redigera', ' '),
(14, '_search', 'Search', 'Suchen', 'Chercher', '', ' ', ' ', 'Sök', ' '),
(15, '_edit_entry', 'Edit entry', 'Eintrag ändern', 'Modifier entré', '', ' ', ' ', 'Redigera posten', ' '),
(16, '_edit_all_entries', 'Edit all entries', 'Alle ändern', 'Modifier toutes les entrées', '', ' ', ' ', 'Redigera alla poster', ' '),
(17, '_ok_', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK'),
(18, '_cancel', 'Cancel', 'Abbruch', 'Annuler', '', ' ', ' ', 'Avbryt', ' '),
(19, '_overview', 'Overview', 'Überblick', 'Présentation', '', ' ', ' ', 'Överblick', ' '),
(20, '_outlets', 'Outlets', 'Outlets', 'Point de vente', '', ' ', ' ', 'Sittningar', ' '),
(21, '_navigation', 'Navigation', 'Navigation', 'Navigation', '', ' ', ' ', 'Navigera', ' '),
(22, '_today', 'Today', 'Heute', 'Aujourd´hui', '', ' ', ' ', 'Idag', ' '),
(23, '_printlist', 'Print list', 'Drucken', 'Imprimer liste', '', ' ', ' ', 'Skriv ut', ' '),
(24, '_users', 'Users', 'Benutzer', 'Utilisateur', '', ' ', ' ', 'Användare', ' '),
(25, '_confirmed_reservations', 'Confirmed reservations', 'Feste Reservierungen', 'Reservation confirmée', '', ' ', ' ', 'Bekräftade reservationer', ' '),
(26, '_canceled_reservations', 'Canceled reservations', 'Stornierte Reservierungen', 'Reservation annulée', '', ' ', ' ', 'Avbokade reservationer', ' '),
(27, '_wait_list', 'Wait list', 'Warteliste', 'Liste d´attente', '', ' ', ' ', 'VÄNTE lista', ' '),
(28, '_search_guest', 'Search Guest', 'Gast Suche', 'Chercher client', '', ' ', ' ', 'Sök Gäst', ' '),
(29, '_search_results', 'Search results', 'Suchergebnisse', 'Resultat de la recherche', '', ' ', ' ', 'Sökresultat', ' '),
(30, '_recent_reservations', 'Recent reservations', 'Letzte Reservierungen', 'Reservation récente', '', ' ', ' ', 'Senast gjorda bokningar', ' '),
(31, '_time', 'Time', 'Zeit', 'Heure', '', ' ', ' ', 'Tid', ' '),
(32, '_guest_name', 'Guest name', 'Gast Name', 'Nom du client', '', ' ', ' ', 'Gästnamn', ' '),
(33, '_pax', 'Pax', 'Pax', 'Couverts', '', ' ', ' ', 'Antal Personer', ' '),
(34, '_phone_room', 'Phone/Room', 'Telefon/Zimmer', 'Téléphone/Chambre', '', ' ', ' ', 'Telefon/Room', ' '),
(35, '_type', 'Type', 'Typ', 'Catégorie', '', ' ', ' ', 'Typ', ' '),
(36, '_note', 'Note', 'Notiz', 'Info', '', ' ', ' ', 'Anteckning', ' '),
(37, '_author', 'Author', 'Autor', 'Auteur', '', ' ', ' ', 'Signatur', ' '),
(38, '_date', 'Date', 'Datum', 'Date', '', ' ', ' ', 'Datum', ' '),
(39, '_status', 'Status', 'Status', 'Stauts', '', ' ', ' ', 'Status', ' '),
(40, '_booked_', 'booked ', 'buchte ', 'réservé', '', ' ', ' ', 'bokade', ' '),
(41, '_people_', 'people ', 'Personen ', 'personne ', '', ' ', ' ', 'personer ', ' '),
(42, '_for_', 'for ', 'für ', 'pour ', '', ' ', ' ', 'den', ' '),
(43, '_or_', 'or ', 'oder ', 'ou ', '', ' ', ' ', 'eller', ' '),
(44, '_canceled_', 'canceled ', 'stornierte', 'annulé', '', ' ', ' ', 'avbokad', ' '),
(45, '_edit_reservation', 'Edit reservation', 'Ändere Reservierung', 'Modifier réservation', '', ' ', ' ', 'Ändrad bokning', ' '),
(46, '_add_reservation', 'Add reservation', 'Neue Reservierung', 'Ajouter réservation', '', ' ', ' ', 'Lägg till bokning', ' '),
(47, '_visits', 'Visits', 'Besuche', 'Visites', '', ' ', ' ', 'Antal besök', ' '),
(48, '_last_visit', 'Last visit', 'Letzter Besuch', 'Dernière visite', '', ' ', ' ', 'Senaste besök', ' '),
(49, '_sentence_16', 'Do not book any more passants!', 'Keine Passanten mehr einbuchen!', 'Désolé, quelque chose c`est mal passé !', '', '', '', 'Ledsen, något har gått fel!', ''),
(50, '_existing_outlets', 'Existing outlets', 'Bestehende Outlets', 'Points de ventes existants', '', ' ', ' ', 'Registrerade sittningar', ' '),
(51, '_add_user', 'Add user', 'Benutzer hinzufügen', 'Ajouter un utilisateur', '', ' ', ' ', 'Lägg till användare', ' '),
(52, '_add_outlet', 'Add outlet', 'Outlet hinzufügen', 'Ajouter un points de ventes', '', ' ', ' ', 'Lägg till sittningar', ' '),
(53, '_name', 'Name', 'Name', 'Nom', '', ' ', ' ', 'Namn', ' '),
(54, '_description', 'Description', 'Beschreibung', 'Description', '', ' ', ' ', 'Beskrivning', ' '),
(55, '_seats', 'Seats', 'Maximale Plätze', 'Nbre de pers max.', '', ' ', ' ', 'Sittplatser', ' '),
(56, '_tables', 'Tables', 'Maximale Tische', 'Nbre de tables max.', '', ' ', ' ', 'Bord', ' '),
(57, '_open_time', 'Open time', 'Öffnungszeit', 'Heure d´ouverture', '', ' ', ' ', 'Öppet tid', ' '),
(58, '_close_time', 'Close time', 'Schliesszeit', 'Heure de fermeture', '', ' ', ' ', 'Stängning tid', ' '),
(59, '_season_start', 'Season start', 'Saison Start', 'Début de la saison', '', ' ', ' ', 'Säsong start', ' '),
(60, '_season_end', 'Season end', 'Saison Ende', 'Fin de la saison', '', ' ', ' ', 'Säsong slut', ' '),
(61, '_day_off', 'Day off', 'Ruhetag', 'Jour de fermeture', '', ' ', ' ', 'Stängda dagar', ' '),
(62, '_new_entry', 'New entry has been added !', 'Eintrag wurde hinzugefügt!', 'Une nouvelle entrée a été ajoutée !', '', ' ', ' ', 'Ny post har registrerats !', ' '),
(63, '_entry_edited', 'Entry has been edited !', 'Eintrag wurde geändert!', 'L’entrée a été mofidiée.', '', ' ', ' ', 'Posten har ändrats !', ' '),
(64, '_entry_deleted', 'Entry deleted!', 'Eintrag wurde gelöscht!', 'Entrée effacée!', '', ' ', ' ', 'Posten borttagen!', ' '),
(65, '_nothing_deleted', 'Nothing deleted!', 'Eintrag wurde nicht gelöscht!', 'Rien est effacé!', '', ' ', ' ', 'Ingen post har blivit borttagen!', ' '),
(66, '_sentence_2', 'Do you really want to delete?', 'Wollen Sie wirklich löschen?', 'Êtes-vous sure de vouloir effacer cet utilisateur?', '', ' ', ' ', 'Vill du ta bort posten?', ' '),
(67, '_enter_password', 'Please enter the password', 'Bitte geben Sie das Passwort ein', 'Svp entrez le mot de passe', '', ' ', ' ', 'Ange lösenord', ' '),
(68, '_wrong_password', 'Wrong password !', 'Falsches Passwort !', 'Mot de passe incorrecte!', '', ' ', ' ', 'Fel lösenord !', ' '),
(69, '_week', 'Week', 'Woche', 'Semaine', '', ' ', ' ', 'vecka', ' '),
(70, '_occupancy_per_week', 'Occupancy per week', 'Belegung pro Woche', 'Ocupation par semaine', '', ' ', ' ', 'Beläggning per vecka', ' '),
(71, '_guest_type_per_month', 'Guest type per month', 'Gastart pro Monat', 'Catégorie de client par mois', '', ' ', ' ', 'Gästtyp per månad', ' '),
(72, '_occupancy_per_month', 'Occupancy per month', 'Belegung pro Monat', 'Occupation par mois', '', ' ', ' ', 'Beläggning per månad', ' '),
(73, '_guest_search', 'Guest Search', 'Gast Suche', 'Recherche de client', '', ' ', ' ', 'Sök gäst', ' '),
(74, '_system', 'System', 'System', 'Système', '', ' ', ' ', 'System', ' '),
(75, '_cancelled', 'Cancelled', 'Storno', 'Annulé', '', ' ', ' ', 'Avbokade', ' '),
(76, '_comments', 'Comments', 'Kommentare', 'Commentaires', '', ' ', ' ', 'Kommentar', ' '),
(77, '_statistics', 'Statistics', 'Statistik', 'Statistiques', '', ' ', ' ', 'Statistik', ' '),
(78, '_export', 'Export', 'Export', 'Export', '', ' ', ' ', 'Export', ' '),
(79, '_info', 'Info', 'Info', 'Info', 'Info', 'Info', 'Info', 'Info', ' Info'),
(80, '_table', 'Table', 'Tisch', 'Table', '', ' ', ' ', 'Bord', ' '),
(81, '_changes', 'Changes', 'Änderungen', 'Changements', '', ' ', ' ', 'Ändringar', ' '),
(82, '_guest_summary', 'Guest summary', 'Gesamt Gäste', 'Synthèse des clients', '', ' ', ' ', 'Gäst sumering', ' '),
(83, '_tables_summary', 'Tables summary', 'Gesamt Tische', 'Synthèse des tables', '', ' ', ' ', 'Bord sumering', ' '),
(84, '_parties_summary', 'Parties summary', 'Gesamt Parties', 'Synthèses des parties', '', ' ', ' ', 'Sällskap sumering', ' '),
(85, '_dollar_revenue_summary', 'Dollar Revenue summary', 'Euro Gesamt Einnahme', 'Synthèses des recettes en euro', '', ' ', ' ', 'Euro Intäkter', ' '),
(86, '_close_window', 'Close Window', 'Fenster schliessen', 'Fermer la fenêtre', '', ' ', ' ', 'Stäng fönstret', ' '),
(87, '_multi_booking', 'Multi Booking<br/>repeat till:', 'Mehrfach Reservierung<br/>Wiederhole bis:', 'Répéter<br/> jusqu´à:', '', ' ', ' ', 'Multi Bokning<br/> repetera till:', ' '),
(88, '_recurring', 'recurring', 'wiederkehrend', 'récurrente', '', ' ', ' ', 'återkommande', ' '),
(89, '_information', 'Information !', 'Hinweis !', 'Information !', '', ' ', ' ', 'Information !', ' '),
(90, '_move_reservation_to', 'Move reservation to', 'Verschiebe Reservierung nach', 'Déplacer la reservation a', '', ' ', ' ', 'Flytta reservationen till', ' '),
(91, '_sentence_5', 'Attention: This table number is already assigned!', 'Achtung: Dieser Tisch wurde schon vergeben!', '', '', ' ', ' ', 'OBS: Detta bordsnummer är redan upptaget!', ' '),
(92, '_sentence_6', 'The restaurant has already opened. Please contact the Maitre!', 'Das Restaurant hat schon geoeffnet. Bitte kontaktieren Sie den zuständigen Maitre!', 'Le service a déjà commencé. Svp contactez le Maitre d´hôtel!', '', ' ', ' ', 'Restaurangen är redan öppen!', ' '),
(93, '_sentence_8', 'Are you sure to reserve such big table? From ', 'Sind Sie sicher das Sie einen so grossen Tisch reservieren wollen? Ab ', 'Couverts : êtes vous sûre de vouloir réserver une table aussi nombreuse? à partir de ', '', ' ', ' ', 'Har du angivit rätt antal personer? Från ', ' '),
(94, '_sentence_9', 'persons we recommend from a quality reason a menu!', 'Personen empfehlen wir aus Qualitätsgründen eine Menüabsprache!', ' pour des raisons de qualité nous recommandons un menu !', '', ' ', ' ', ' För stora sällskap måste vi ta förbeställning av för och varmrätt!', ' '),
(95, '_paid', 'Paid', 'Zahlung', 'payé', '', ' ', ' ', 'Betalning', ' '),
(96, '_shipped', 'shipped', 'Versendet', 'expédié', '', ' ', ' ', 'Försändelse', ' '),
(97, '_adress', 'Address', 'Adresse', 'Adresse', '', ' ', ' ', 'Adress', ' '),
(98, '_area_code', 'ZIP Code-City', 'PLZ-Ort', 'Code postal', '', ' ', ' ', 'Postnr', ' '),
(99, '_email', 'Email', 'Email', 'Courriel', '', ' ', ' ', 'Email', ' '),
(100, '_paid_by', 'Paid by', 'Bez. per', 'Payé par', '', ' ', ' ', 'Betald av', ' '),
(101, '_parking', 'Parking', 'Parken', 'Parking', '', ' ', ' ', 'Parkering', ' '),
(102, '_discount', 'Discount', 'GdH', 'Réduction', '', ' ', ' ', 'Rabatt', ' '),
(103, '_password', 'Password', 'Passwort', 'Mot de passe', '', ' ', ' ', 'Lösenord', ' '),
(104, '_ticket_system', 'Ticket system', 'Ticketsystem', '', '', ' ', ' ', 'Biljett system', ' '),
(105, '_ticket_price', 'Price', 'Preis', 'Prix', '', ' ', ' ', 'Pris', ' '),
(106, '_payment', 'Payment', 'Bezahlt', 'Payé', '', ' ', ' ', 'Betalt', ' '),
(107, '_shipping', 'Shipping', 'Versand', 'Expédition', '', ' ', ' ', 'Försändelse', ' '),
(108, '_sent', 'Sent', 'Ausgang', 'Envoyé', '', ' ', ' ', 'Skickad', ' '),
(109, '_timecontrol', 'Timecontrol', 'Timecontrol', 'Contrôle du temps', '', ' ', ' ', 'Tidkontroll', ' '),
(110, '_webform', 'Online booking', 'Online Buchung', '', '', ' ', ' ', '', ' '),
(111, '_tautologous_booking', 'Tautologous booking: This guest has a second booking on this day', 'Doppelbuchung : Dieser Gast hat noch eine andere Buchung an diesem Tag.', 'Double reservation : ce client a une seconde reservation le même jour.', '', ' ', ' ', 'Dubbelbokning: Denna gäst har ännu en bokning denna dag.', ' '),
(112, '_sentence_11', 'This is an older reservation.', 'Diese Reservierung ist schon etwas älter.', 'Ceci est une ancienne réservation.', '', ' ', ' ', 'Detta är en gammal bokning.', ' '),
(113, '_sentence_13', 'Reservation was done after maitre message.', 'Die Reservierung wurde nach dem Maitre Hinweis getätigt.', 'La reservation a été faite après le message du Maitre d’hôtel.', '', ' ', ' ', 'Reservationen var gjord efter hovmästarens kommentar.', ' '),
(114, '_sorry', 'Sorry, something goes wrong!', 'Uups, es ging etwas schief!', 'Désolé, quelque chose c`est mal passé !', '', '', ' ', 'Ledsen, något har gått fel!', ' '),
(115, '_general', 'General', 'Allgemein', 'Général', '', ' ', ' ', 'Allmänt', ' '),
(116, '_fill_out', 'Fill out for sending a confirmation.', 'Zum Zusenden einer Bestätigung ausfüllen.', 'Remplissez pour recevoir un courriel de confirmation.', '', ' ', ' ', 'Fyll i för att skicka en bekräftelse.', ' '),
(117, '_confirmation_email', 'Confirmation Email', 'Bestätigungsemail', 'Courriel de confirmation', '', ' ', ' ', 'Bekräftelse email', ' '),
(118, '_database', 'Database', 'Datenbank', 'Base de données', '', ' ', ' ', 'Databas', ' '),
(119, '_path', 'Path', 'Pfad', 'Chemin', '', ' ', ' ', 'Sökväg', ' '),
(120, '_language', 'Language', 'Sprache', 'Langue', '', ' ', ' ', 'Språk', ' '),
(121, '_title', 'Title', 'Titel', 'Titre', '', ' ', ' ', 'Titel', ' '),
(122, '_booknum', 'Booking number', 'Buchungsnummer', '', '', '', '', '', ''),
(123, '_zip', 'ZIP', 'PLZ', '', '', '', '', '', ''),
(124, '_english', 'English', 'Deutsch', 'Français', '', ' ', ' ', 'Svenska', ' '),
(125, '_international', 'International', 'Englisch', 'Anglais', '', ' ', ' ', 'Engelska', ' '),
(126, '_before', 'before', 'zuvor', '', '', '', '', '', ''),
(127, '_till_', 'till', 'bis', '', '', ' ', ' ', 'till', ' '),
(128, '_at_', 'at', 'um', '', '', ' ', ' ', ' ', ' '),
(129, '_reserved', 'reserved', 'reserviert', '', '', ' ', ' ', ' ', ' '),
(130, '_active', 'Active', 'Aktiv', '', '', '', '', '', ''),
(131, '_retype', 'Retype', 'Wiederhole', '', '', '', '', '', ''),
(132, '_cuisine_style', 'Cuisine Style', 'Küchenrichtung', '', '', '', '', '', ''),
(133, '_sp_events', 'Special Event', 'Sonderveranstaltung', '', '', '', '', '', ''),
(134, '_subject', 'Subject', 'Betreff', '', '', '', '', '', ''),
(135, '_open_to', 'Open to', 'Frei für', '', '', '', '', '', ''),
(136, '_contact', 'Contact', 'Kontakt', '', '', '', '', '', ''),
(137, '_advertise_start', 'Start advertise', 'Werbung starten', '', '', '', '', '', ''),
(138, '_days', 'Days', 'Tage', '', '', '', '', '', ''),
(139, '_email_subject', 'Reservation confirmation for', 'Reservierungsbestätigung für', '', '', '', '', '', ''),
(140, '_dear_mr', 'Dear Mr.', 'Sehr geehrter Herr', 'Cher Monsieur', '', ' ', ' ', 'Bästa herr', ' '),
(141, '_dear_mrs', 'Dear Mrs.', 'Sehr geehrte Frau', 'Cher Madame', '', ' ', ' ', 'Bäste fru', ' '),
(142, '_dear_sirs_and_madams', 'Dear Sirs and Madams', 'Sehr geehrte Damen und Herren', 'Chers Messieurs et Madames', '', ' ', ' ', 'Bäste herr och fru', ' '),
(143, '_dear_family', 'Dear Family', 'Liebe Familie', 'Chère famille', '', ' ', ' ', 'Kära familj', ' '),
(144, '_property', 'Property', 'Anwesen', '', '', '', '', '', ''),
(145, '_M_', 'Mr.', 'Herr', 'Monsieur', '', '', '', 'Herr', ''),
(146, '_W_', 'Mrs.', 'Frau', 'Madame', '', '', '', 'Fru', ''),
(147, '_F_', 'Fam.', 'Fam.', 'Famille', '', '', '', 'Familj', ''),
(148, '_C_', 'Company', 'Firma', 'Société', '', '', '', 'Företag', ''),
(149, '_mail', 'Invoice', 'Rechnung', '', '', '', '', '', ''),
(150, '_room', 'Room', 'Zimmer', 'Chambre', '', '', '', '', ''),
(151, '_HG_', 'Inhouse Guest', 'Hausgast', '', '', '', '', '', ''),
(152, '_PASS_', 'Passer by', 'Passant', 'Passants', '', '', '', '', ''),
(153, '_WALK_', 'Walk in', 'Walk in', '', '', '', '', '', ''),
(154, '_create', 'Create', 'Anlegen', '', '', '', '', '', ''),
(155, '_year', 'Year', 'Jahr', '', '', '', '', '', ''),
(156, '_created', 'created at', 'angelegt am', '', '', '', '', '', ''),
(157, '_back', 'Back', 'Zurück', '', '', '', '', '', ''),
(158, '_detail', 'Detail', 'Detail', 'Detail', '', '', '', '', ''),
(159, '_passerby', 'Passerby', 'Passanten', 'Passants', '', '', '', '', ''),
(160, '_duration', 'Residence time', 'Verweildauer', '', '', '', '', '', ''),
(161, '_history', 'Guest History', 'Gast Historie', '', '', '', '', '', ''),
(162, '_no_', 'No', 'Nein', 'No', '', '', '', '', ''),
(164, '_yes_', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK'),
(165, '_statuslist', 'NYA,Arrived,Seated,Parked,Departed,No Show', 'NYA,Angekommen,Plaziert,an Bar,Gegangen,No Show', '', '', '', '', '', ''),
(166, '_delete_all_entries', 'delete series', 'serie löschen', '', '', '', '', '', ''),
(167, '_settings', 'Settings', 'Einstellungen', '', '', '', '', '', ''),
(168, '_hello', 'Hello', 'Guten Tag', '', '', '', '', '', ''),
(170, '_city', 'City', 'Stadt', '', '', '', '', '', ''),
(171, '_phone', 'Phone', 'Telefon', '', '', '', '', '', ''),
(172, '_fax', 'Facsimile', 'Telefax', '', '', '', '', '', ''),
(173, '_country', 'Country', 'Land', '', '', '', '', '', ''),
(174, '_img', 'Image', 'Bild', '', '', '', '', '', ''),
(175, '_free', 'free', 'frei', '', '', '', '', '', ''),
(177, '_email_confirmation_en', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s'),
(178, '_email_subject_en', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for ', 'Reservation confirmation for '),
(163, '_email_confirmation', 'Thank you very much for your reservation in our %s.\r\nWith pleasure we confirm your reservation for %s person(s) on %s at %s.\r\n\r\nIf you want cancel your reservation please use your booking number \'%s\' at the homepage.\r\n\r\nWe wish you an enjoyable stay at our restaurant and are looking forward to your visit!\r\n\r\nYours\r\n %s', 'Vielen Dank für Ihre Reservierung in unserem %s.\r\nGerne haben wir für Sie %s Person(en) am %s um %s reserviert.\r\n\r\nWenn Sie Ihre Reservierung stornieren möchten, können Sie dies mit der Buchungsnummer \'%s\' auf der Homepage vornehmen.\r\n\r\nWir wünschen Ihnen einen angenehmen Aufenthalt in unserem Restaurant und freuen uns auf Ihren Besuch!\r\n\r\nBeste Grüße\r\n%s', '', '', '', '', '', '');");


echo "<li><strong>The translation texts had been inserted.</strong></li>";

?>
